# Generated by Django 2.2.6 on 2019-10-31 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SandFURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default=None)),
                ('FURL', models.TextField(default=None)),
                ('SURL', models.TextField(default=None)),
                ('howlongUsed', models.IntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 31, 21, 11, 24, 583042, tzinfo=utc))),
            ],
        ),
    ]
